---
  model: 
    downsampling:
      optim_args:
        task_lr_decay: 
          - 50
          - 200
  data:
    test_only_images:
      - '0868.png'
    data_test:
      - DIV2K
  degradation_operations: 
    test: 
      - name: 'kernelganfkp_kernels_x4_clean'
        lr_folder: KernelGANFKP_lr_x4_clean
        kernel:
          kernel_folder: KernelGANFKP_gt_k_x4_clean
  optim:
    evaluation_task_steps: 
      - 0
      - 25
      - 50
      - 100
      - 200
  train:
    save_kernels:
      - 0
      - 25
      - 50
      - 100
      - 200
    scale: 4
    save_results: true
    test_only: true
    evaluate_non_blind:
      model: usrnet